import { getDb } from '@/lib/firebase';
import { collection, getDocs, query, where, orderBy, limit } from 'firebase/firestore';
import { Tenant } from '@/types/tenant';
import { notFound } from 'next/navigation';
import Link from 'next/link';

interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  categoryName: string;
  categorySlug: string;
  publishedAt: Date;
  author: string;
}

async function getTenantBySlug(slug: string): Promise<Tenant | null> {
  const db = getDb();
  const tenantsQuery = query(
    collection(db, 'tenants'),
    where('slug', '==', slug),
    limit(1)
  );
  const snap = await getDocs(tenantsQuery);
  if (snap.empty) return null;
  return { id: snap.docs[0].id, ...snap.docs[0].data() } as Tenant;
}

async function getArticles(tenantId: string): Promise<Article[]> {
  const db = getDb();
  const articlesQuery = query(
    collection(db, `tenants/${tenantId}/articles`),
    where('status', '==', 'published'),
    orderBy('publishedAt', 'desc'),
    limit(20)
  );
  const snap = await getDocs(articlesQuery);
  return snap.docs.map((doc) => {
    const data = doc.data();
    return {
      id: doc.id,
      title: data.title,
      slug: data.slug,
      excerpt: data.excerpt,
      categoryName: data.categoryName,
      categorySlug: data.categorySlug,
      publishedAt: data.publishedAt?.toDate?.() || new Date(),
      author: data.author,
    } as Article;
  });
}

export default async function TenantPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const tenant = await getTenantBySlug(slug);

  if (!tenant) {
    notFound();
  }

  const articles = await getArticles(tenant.id);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b shadow-sm">
        <div className="max-w-6xl mx-auto px-4 py-6">
          <h1 className="text-3xl font-bold text-gray-900">{tenant.businessName}</h1>
          <p className="text-gray-500 mt-1">
            Serving {tenant.serviceArea.city}, {tenant.serviceArea.state}
          </p>
        </div>
      </header>

      {/* Navigation */}
      <nav className="bg-gray-900 text-white">
        <div className="max-w-6xl mx-auto px-4 py-3 flex gap-6 overflow-x-auto">
          {tenant.categories.filter(c => c.enabled).map((category) => (
            <Link
              key={category.id}
              href={`/${tenant.slug}/${category.slug}`}
              className="text-sm font-medium hover:text-blue-300 whitespace-nowrap"
            >
              {category.name}
            </Link>
          ))}
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-6xl mx-auto px-4 py-8">
        {articles.length === 0 ? (
          <div className="text-center py-12 bg-white rounded-lg border">
            <h2 className="text-xl font-semibold text-gray-700">Coming Soon</h2>
            <p className="text-gray-500 mt-2">
              Articles are being generated by our AI journalists. Check back soon!
            </p>
          </div>
        ) : (
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {articles.map((article) => (
              <article
                key={article.id}
                className="bg-white rounded-lg border shadow-sm overflow-hidden hover:shadow-md transition-shadow"
              >
                <div className="p-5">
                  <span className="text-xs font-semibold text-blue-600 uppercase tracking-wide">
                    {article.categoryName}
                  </span>
                  <h2 className="mt-2 text-lg font-bold text-gray-900 line-clamp-2">
                    <Link href={`/${tenant.slug}/article/${article.slug}`}>
                      {article.title}
                    </Link>
                  </h2>
                  <p className="mt-2 text-gray-600 text-sm line-clamp-3">
                    {article.excerpt}
                  </p>
                  <div className="mt-4 flex items-center justify-between text-xs text-gray-500">
                    <span>{article.author}</span>
                    <time>
                      {article.publishedAt.toLocaleDateString('en-US', {
                        month: 'short',
                        day: 'numeric',
                        year: 'numeric',
                      })}
                    </time>
                  </div>
                </div>
              </article>
            ))}
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 mt-12">
        <div className="max-w-6xl mx-auto px-4 py-8 text-center text-sm">
          <p>&copy; {new Date().getFullYear()} {tenant.businessName}. All rights reserved.</p>
          <p className="mt-2">
            Powered by{' '}
            <a href="https://newsroomaios.com" className="text-blue-400 hover:underline">
              Newsroom AIOS
            </a>
          </p>
        </div>
      </footer>
    </div>
  );
}
